# Generated by Django 5.0.3 on 2024-03-09 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='emp_efficiency',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='tool',
            name='tool_efficiency',
            field=models.FloatField(default=None, null=True),
        ),
    ]
